language: python

build_image: vauxoo/odoo-80-image-shippable-auto

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  # shippable compatibility
  - sudo mkdir -p /etc/ssl/private-copy; sudo mkdir -p /etc/ssl/private; sudo mv /etc/ssl/private/* /etc/ssl/private-copy/; sudo rm -r /etc/ssl/private; sudo mv /etc/ssl/private-copy /etc/ssl/private; sudo chmod -R 0700 /etc/ssl/private; sudo chown -R postgres /etc/ssl/private
  - sudo su -c "sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c "config_file=/etc/postgresql/9.3/main/postgresql.conf" > /tmp/pg.log 2>&1 & sleep 5s"

  - createdb employee_employee
  - pip install flake8

script:
  - psql -d employee_employee -a -f ${TRAVIS_BUILD_DIR}/employee_vauxoo.sql
  - psql -d employee_employee -c "SELECT * FROM employee" >employee.out && cat employee.out
  - psql -d employee_employee -c "SELECT * FROM employee_department" >employee_department.out && cat employee_department.out
  - psql -d employee_employee -c "SELECT * FROM employee_hobby" >employee_hobby.out && cat employee_hobby.out
  - flake8 ${TRAVIS_BUILD_DIR}/ --exclude=__init__.py
  - PYTHONPATH=${TRAVIS_BUILD_DIR} python -c "from calculator import calculator_class;obj=calculator_class();mysum=obj.sum([1,2,3,4,5,6]);exit(not (mysum==21 or mysum=='not implement yet'))"
  - PYTHONPATH=${TRAVIS_BUILD_DIR} python -c "from primes import prime_class;obj=prime_class();primes_result=all(map(lambda num: obj.is_prime(num) == 'not implement yet' or obj.is_prime(num), [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107]));exit(not primes_result)"
  - PYTHONPATH=${TRAVIS_BUILD_DIR} python -c "from primes import prime_class;obj=prime_class();no_primes_result=all(map(lambda num: obj.is_prime(num) != 'not implement yet' and obj.is_prime(num), [1,4,6,8,9,10,12,14,15,16,18,20,21,22,24,25]));print "no_primes_result",no_primes_result;exit(no_primes_result)"
  # - python ${TRAVIS_BUILD_DIR}/calculator_test.py  # interactive mode. TODO: test it a interactive python script.
